source('utils/utils.r')
source('model/params.r')
source('model/system.r')
source('model/output.r')
source('model/plot.r')

t = def.t(t1=120)
P = def.params()
R = sys.run(P,t)
g = plot.out(out.prevalence(R,health='vax',strat=c('city','risk')),color='city',linetype='risk'); print(g)
g = plot.out(out.prevalence(R,health='inf',strat=c('city','risk'),prop=F),color='city',linetype='risk'); print(g)
g = plot.out(out.incidence(R,strat=c('city','risk'),rate=F),color='city',linetype='risk'); print(g)
g = plot.out(out.incidence(R,strat=c('city','risk')),color='city',linetype='risk'); print(g)
