source('utils/utils.r')
source('model/params.r')
source('model/system.r')
source('model/output.r')
source('model/plot.r')

t = def.t(t1=120)
P = def.params()
R = sys.run(P,t)
g = plot.out(out.prevalence(R,health='vax',aggr=F,prop=F),color='city',linetype='risk'); print(g)
g = plot.out(out.prevalence(R,health='inf',aggr=F,prop=F),color='city',linetype='risk'); print(g)
g = plot.out(out.incidence(R,health='sus',aggr=F),color='city',linetype='risk'); print(g)
